baseURL = "https://tondomaine.com/"
languageCode = "en-us"
title = "Seys"
theme = "PaperMod"

[params]
  env = "production"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/RootOrRiot"
  weight = 20
